In [2]:
import pandas as pd

In [3]:
#Sort

# Data Source Link: https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset
data = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')

In [4]:
#DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, kind=â€™quicksortâ€™, na_position=â€™lastâ€™)
#by = column names to sort by that
#axis  = 0 rows, 1 for columns
#if inplace = True, will make changes in passed data
#kind: sort algorithm, include quicksort, mergesort or heapsort
#na_position: 'last' or 'first' to set position of null values. 'last' is default 

#first let's see the data
data

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [7]:
#Now let's sort using the function. I want to sort  by Heart Rate

out = data.sort_values("Heart Rate", axis = 0, ascending = True, inplace = False, na_position= 'last')

#let's see the results
out

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
186,187,Female,43,Teacher,6.7,7,45,4,Overweight,135/90,65,6000,Insomnia
256,257,Female,45,Teacher,6.6,7,45,4,Overweight,135/90,65,6000,Insomnia
257,258,Female,45,Teacher,6.6,7,45,4,Overweight,135/90,65,6000,Insomnia
258,259,Female,45,Teacher,6.6,7,45,4,Overweight,135/90,65,6000,Insomnia
259,260,Female,45,Teacher,6.6,7,45,4,Overweight,135/90,65,6000,Insomnia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,6,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
277,278,Male,49,Doctor,8.1,9,85,3,Obese,139/91,86,3700,Sleep Apnea
276,277,Male,49,Doctor,8.1,9,85,3,Obese,139/91,86,3700,Sleep Apnea

In [10]:
#Now let's sort different!
#We want to sort different columns, but each in order we want (ascending or descending)
# Sort two columns, Physical Activity Level and Heart Rate, first ascending next descending 
out2 = data.sort_values(by= ["Physical Activity Level", "Heart Rate"], axis = 0,
                        ascending=[True, False], inplace= False)

out2

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,6,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
33,34,Male,31,Doctor,6.1,6,30,8,Normal,125/80,72,5000,NaN
35,36,Male,31,Doctor,6.1,6,30,8,Normal,125/80,72,5000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,219,Male,43,Engineer,7.8,8,90,5,Normal,130/85,70,8000,Sleep Apnea
163,164,Male,40,Lawyer,7.9,8,90,5,Normal,130/85,68,8000,NaN
164,165,Male,40,Lawyer,7.9,8,90,5,Normal,130/85,68,8000,NaN
341,342,Female,56,Doctor,8.2,9,90,3,Normal Weight,118/75,65,10000,NaN
342,343,Female,56,Doctor,8.2,9,90,3,Normal Weight,118/75,65,10000,NaN